version: "3.3"

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - /Users/thiago.nogueira/.rd/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    env_file: .env