version: '3'

volumes:
  mongodb:
  graylog:
  elasticsearch:

services:
  # Graylog Server
  graylog:
    image: graylog/graylog:4.2
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://localhost:9000/
    ports:
      - 9000:9000
      - 514:514
      - 514:514/udp
      - 12201:12201
      - 12201:12201/udp
    links:
      - mongo
      - elasticsearch
    depends_on:
      - mongo
      - elasticsearch
    volumes:
      - graylog:/usr/share/graylog/data/journal
    networks:
      - graylog-network

  # MongoDB
  mongo:
    image: mongo:4.4
    volumes:
      - mongodb:/data/db
    networks:
      - graylog-network

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - "discovery.type=single-node"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    networks:
      - graylog-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    environment:
      - NGINX_SERVER_NAME=localhost

networks:
  graylog-network:
    driver: bridge
