apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-broker
    service: kafka-broker
  name: kafka-broker
  namespace: local
spec:
  ports:
    - name: internal
      port: 29092
      targetPort: 29092
    - name: external
      port: 30092
      targetPort: 9092
      nodePort: 30092
  type: NodePort
  selector:
    app: kafka-broker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-broker
  name: kafka-broker
  namespace: local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
        service: kafka-broker
    spec:
      hostname: kafka-broker
      containers:
        - name: kafka-broker
          env:
            - name: KAFKA_BROKER_ID
              value: '1'
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zoo1:2181
            - name: KAFKA_ADVERTISED_LISTENERS
              value: INTERNAL://kafka-broker:29092,EXTERNAL://kafka-broker:9092
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            - name: KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: CONFLUENT_SUPPORT_CUSTOMER_ID
              value: 'anonymous'
            - name: KAFKA_JMX_PORT
              value: '9101'
            - name: KAFKA_JMX_HOSTNAME
              value: 'localhost'
          image: confluentinc/cp-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 29092
            - containerPort: 9092