apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-ui
  name: kafka-ui-service
  namespace: local
spec:
  ports:
    - name: web
      port: 8080
      targetPort: 8080
  selector:
    app: kafka-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-ui
  name: kafka-ui
  namespace: local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
        service: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          ports:
            - containerPort: 8080
              name: web
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: "kafka-broker"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS
              value: kafka-broker:29092
            - name: KAFKA_CLUSTERS_0_SCHEMAREGISTRY
              value: http://schema-registry-service:30081
            - name: DYNAMIC_CONFIG_ENABLED
              value: "true"
