apiVersion: v1
kind: ServiceAccount
metadata:
  name: alpine-service-account
  namespace: local
  labels:
    account: alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine
  namespace: local
  labels:
    name: alpine
    app: alpine
    application: alpine
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  serviceAccountName: alpine-service-account
  containers:
    - name: alpine
      image: alpine
      command: [ "/bin/sleep", "infinite", "apk update", "apk add bind-tools", "apk add busybox-extras" ]
  restartPolicy: OnFailure