---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: google
    showSearchSuggestions: true 
    target: _blank

- datetime:
    text_size: xl
    format:
        dateStyle: short
        timeStyle: short
        hourCycle: h23